// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMWTuesmMMRfR_LVsCijdmw5xnb7E0eto',
    appId: '1:740232934971:web:579a3b5250e7e8a3e38e1e',
    messagingSenderId: '740232934971',
    projectId: 'rentalmobil-ef0ad',
    authDomain: 'rentalmobil-ef0ad.firebaseapp.com',
    storageBucket: 'rentalmobil-ef0ad.firebasestorage.app',
    measurementId: 'G-MM51GKYXCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC41MjFPHrQvt77s4_SmQpA__KYelIC4Qo',
    appId: '1:740232934971:android:6d04511a640b09c3e38e1e',
    messagingSenderId: '740232934971',
    projectId: 'rentalmobil-ef0ad',
    storageBucket: 'rentalmobil-ef0ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqipW_-7Eb0TKkliCl_td8LbfOfG_VAH0',
    appId: '1:740232934971:ios:8a1da28a0df2a151e38e1e',
    messagingSenderId: '740232934971',
    projectId: 'rentalmobil-ef0ad',
    storageBucket: 'rentalmobil-ef0ad.firebasestorage.app',
    iosBundleId: 'com.example.rentalMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqipW_-7Eb0TKkliCl_td8LbfOfG_VAH0',
    appId: '1:740232934971:ios:8a1da28a0df2a151e38e1e',
    messagingSenderId: '740232934971',
    projectId: 'rentalmobil-ef0ad',
    storageBucket: 'rentalmobil-ef0ad.firebasestorage.app',
    iosBundleId: 'com.example.rentalMobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMWTuesmMMRfR_LVsCijdmw5xnb7E0eto',
    appId: '1:740232934971:web:1fb694ba8acf3323e38e1e',
    messagingSenderId: '740232934971',
    projectId: 'rentalmobil-ef0ad',
    authDomain: 'rentalmobil-ef0ad.firebaseapp.com',
    storageBucket: 'rentalmobil-ef0ad.firebasestorage.app',
    measurementId: 'G-SLGER3VXXL',
  );
}
